### ISSUE TITLE
Color formatting looks kindof broken?

### ISSUE THREAD

**Issue by bengourley** [yoshuawuyts/choo-log#16]
Hey, haven't had a chance to poke around to see what's up with this but see the attached screenshot… a hex colour code is being output of the end of each line, rather than colouring the line.

![screen shot 2016-09-29 at 12 03 53](https://cloud.githubusercontent.com/assets/609579/18951560/bb71b1e8-863d-11e6-8d65-70b619a5f068.png)

**Comment by timwis** [comment]
Yeah same here :/

**Comment by yoshuawuyts** [comment]
ohh, yeah that's not good - might be a regression from https://github.com/yoshuawuyts/choo-log/commit/2edb4405dd79e25a7190dce8552f05fc4b173c98

**Comment by bengourley** [comment]
Cool, just pinned back to 1.4.0 for now 😄

**Comment by yoshuawuyts** [comment]
cc/ @mixmix could you take a look at this?

**Comment by mixmix** [comment]
D: I'll take a look if I have time. I think this is a side-effect of chrome / firefox difference in how they log colors

**Comment by mixmix** [comment]
@bengourley @timwis can you confirm what browsers you're using.

**Comment by timwis** [comment]
Chrome 53 on OS X. 1.4.0 works fine for me, but 1.4.1 does what's described above

**Comment by bengourley** [comment]
Chrome 53.0.2785.143 on OS X, same as above :)

**Comment by tgfjt** [comment]
Same on Chrome 54.0.2840.59 😭

**Comment by yoshuawuyts** [comment]
fix very much welcome! - bit busy rn to do it myself; and I'd rather not revert the FF support :/

**Comment by tgfjt** [comment]
How about this?
Somebody helps to review this? :bowtie: 
https://github.com/yoshuawuyts/choo-log/pull/21

**Comment by yoshuawuyts** [comment]
This should be fixed now :D
