### ISSUE TITLE
Support choo@3

### ISSUE THREAD

**Issue by ngryman** [yoshuawuyts/choo-log#22]
Hey,

It seems that `choo@4` swaps `data` and `state` parms in reducers and effects, making the latest version of `choo-log` to report wrong diffs when used with `choo@3`.

Do you think it would be easy to support both versions of `choo`? Or mention in the readme that only `choo-log@1.4.1` works with `choo@3`?

Thanks!

**Comment by yoshuawuyts** [comment]
Hey, I'm very sorry but I replied from email and somehow it didn't come through. I wrote this:

> Yeah, I've run into this before - this is definitely an issue with peer dependencies hey. I think pinning down the peer dependencies in package.json would make sense (e.g. >= 4.0) and then also mention it in the docs.
> 
> PR for either (or both) welcome! :sparkles:

**Comment by ngryman** [comment]
No problem for the PR. I'm just waiting to see what is decided in https://github.com/yoshuawuyts/choo/issues/287.

**Comment by yoshuawuyts** [comment]
Yeah, I've run into this before - this is definitely an issue with peer
dependencies hey. I think pinning down the peer dependencies in
package.json would make sense (e.g. >= 4.0) and then also mention it in the
docs.

PR for either (or both) welcome! :sparkles:

**Comment by yoshuawuyts** [comment]
seems like my emails from a few days ago are finally coming through 😓 - sorry about that

**Comment by ungoldman** [comment]
@yoshuawuyts It seems like choo-log is outpacing choo quite a bit -- am I correct in understanding latest published version of choo-log does not work with latest published version of choo?

**Comment by yoshuawuyts** [comment]
Yeah, only works with choo 4 - it's usable now tho, so if you dont mind
docs being a bit thin I can recommend switching (:

**Comment by yoshuawuyts** [comment]
That said: should we like make it check peer deps? This is starting to
become rough hah :(

**Comment by ungoldman** [comment]
If peer deps have breaking changes on a regular basis, helps to surface that to the user. Ideally breaking changes are a rarity 😜

**Comment by yoshuawuyts** [comment]
Hahaha, yeah sorryyyyyyyy - gonna try and not flip the arg order around too
often :p

**Comment by yoshuawuyts** [comment]
did it again; I'm sorry - choo's API is not gonna change anymore thooooo sooooooo... closing :P
