### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by YerkoPalma** [yoshuawuyts/choo-log#4]
Or there is any reason why the project has no tests?

**Comment by yoshuawuyts** [comment]
uehhh, yeah - was constrained on time and there's not a lot to test haha :sparkles: - should probs split the highlighting function into a separate package / create a separate logger. Think linting here is probs enough for the time being, though if you want to get fancy PRs are def welcome :grin:

**Comment by YerkoPalma** [comment]
I just though on testing the results of console.log after some choo hooks, looking at [this](http://stackoverflow.com/questions/7246884/detecting-console-log-calls#answer-7246931). I'll play with this around, if I get anything good, I'll submit a PR

**Comment by yoshuawuyts** [comment]
Oh yeah, could always monkey patch - def found eyeballing the results to be quite effective so far haha

**Comment by yoshuawuyts** [comment]
nah, kinda don't want to - takes too long and we shouldn't be touching this code too much anyway. If anyone else wants to add tests please feel free to C:

The logger is now also in a separate package (nanologger). Thanks!
