### ISSUE TITLE
Uncaught TypeError: Cannot read property 'duration' of undefined

### ISSUE THREAD

**Issue by s3ththompson** [yoshuawuyts/choo-log#57]
Hiya!

I'm loving choo & choo-log, but just started seeing this error show up in console:
`Uncaught TypeError: Cannot read property 'duration' of undefined at renderPerformance (bundle.js:1541)` which comes from `window.performance.getEntriesByName('choo:render')` returning an empty array.

Let me know if having my app would help repro, but I'm guessing it's just some sort of race with the performance mark/measure stuff in choo proper.

Thanks!

**Comment by reminyborg** [comment]
This happens if you call render before `DOMContentLoaded` is called.

To solve it i wrapped adding my models in a `.on('DOMConentLoaded', /* effects and models */)`
```javascript
app.use((state, emitter) => { emitter.on('DOMContentLoaded', () => {
  app.use(todos)
})})
```
