### ISSUE TITLE
Colors in Chrome devtools are too light

### ISSUE THREAD

**Issue by rmariuzzo** [yoshuawuyts/choo-log#78]
![localhost 8080 2017-06-27 19-47-55](https://user-images.githubusercontent.com/439839/27614736-98f4563e-5b71-11e7-8720-3d4a45d7682b.png)

I feel the colors are too light for Chrome's dev tool when not using the dark theme.

**Comment by yoshuawuyts** [comment]
Yeah good point; I never use the light theme so it doesn't bother me too
much, but at least allowing it to be changed would be good I reckon. We
could make colors a property on the instance of nanologger, and then have
an option in choo-log to allow for a custom map of colors to be passed in.
https://github.com/yoshuawuyts/nanologger/blob/master/index.js#L17-L29 - PR
welcome to both!

**Comment by ghost** [comment]
I created the optional parameter part in the nanologger repository: https://github.com/yoshuawuyts/nanologger/pull/5. If everything is okay with that, I can submit the missing functionality here. :)
