### ISSUE TITLE
Correct sourcemap line ?

### ISSUE THREAD

**Issue by antenando** [yoshuawuyts/choo-log#83]
Using Chrome Version 60.0.3112.90 (Official Build) (64-bit)
Browserify@14.4.0 and choo-log@**7.2.1** here:

Wherever I `emitter.emit('log:debug', 'whatever')` I always get `/node_modules/nanologger/index.js:145` as the source file

A simple `console.log('whatever')` points me to the correct source file, though

Am I doing something wrong ?

**Comment by antenando** [comment]
Just tested another project with React and Nanologger bundled by webpack and the very same behavior happens as well. Guess the problem is in Nanologger then.

**Comment by tgfjt** [comment]
The reason is that `emitter.emit('log:debug', 'whatever')` reachs this line:
https://github.com/choojs/nanologger/blob/master/index.js#L145

I'm not sure but `nanologger` had better to use `console.log.bind`.
I think It's difficult issue for nanologger.

**Comment by antenando** [comment]
Is this something worthy to address in Nanologger's issues ?

**Comment by tgfjt** [comment]
@antenando Yes, I think so, it's a bit difficult to resolve tho!

**Comment by yoshuawuyts** [comment]
Closing because we're archiving this repository — it is now part of `choo-devtools`. Thanks!
