### ISSUE TITLE
Uncaught TypeError: Cannot read property 'duration' of undefined

### ISSUE THREAD

**Issue by YerkoPalma** [yoshuawuyts/choo-log#84]
I have this error
![image](https://user-images.githubusercontent.com/5105812/29716365-7de2d710-8981-11e7-8d94-e127c1c181cb.png)

And tracked it down to choo-log [here](https://github.com/choojs/choo-log/blob/master/index.js#L58).
Not sure what I could be doing wrong.

Also, tried to avoid it disabling timing, as the readme says, but it doesn't do anything. Actually, I can't find where are those options used in the source, only the colors options is passed?

**Comment by yoshuawuyts** [comment]
Looks like it's reading a value from `nanotiming`, and somehow the value is
not available. Is this a consistent error? Are you perhaps doing anything
with performance observers. Also: what chrome version are you running?

**Comment by YerkoPalma** [comment]
I'm using chrome 60.0.3112.113 64 bits.
I'm not doing anything with performance observer as far as I know. I'm using choo with choo-log and choo-service-worker. Also using Nanocomponent and lightgallery.js, but I'm pretty sure non of those is messing with performance API.

Also this error is non blocking, in fact, after that error other events get logged correctly with their respective time, even if I trigger the same event that before throw the error...

**Comment by yoshuawuyts** [comment]
Yeah, there's also a chance that Chrome itself is glitching here. I've
reported errors to the Chrome team before about the Performance API, do not
surprised if other edge cases exist.

**Comment by YerkoPalma** [comment]
haha Chrome...

> Also, tried to avoid it disabling timing, as the readme says, but it doesn't do anything

That's differnet, I did it like this.

```js
app.use(require('choo-log')({ timing: false }))
```

Is that the way to pass options? If it is, why isn't disabling timing?

**Comment by yoshuawuyts** [comment]
Timings are part of choo, so you need to set a value on local storage -
check nanotiming docs for the right one

**Comment by kareniel** [comment]
re: check [nanotiming docs](https://github.com/choojs/nanotiming)

leaving this here in case it might be useful to someone going through the thread:
```js
app.use(log())
window.localStorage.DISABLE_NANOTIMING = true
```

**Comment by yoshuawuyts** [comment]
Closing because we're archiving this repository — it is now part of `choo-devtools`. Thanks!
